{{ config
(
    materialized = 'incremental',
    unique_key = ['TRANSACTION_HASH','TRACE_ID']
)
}}

SELECT 
BLOCK_TIMESTAMP,
date_trunc('day',BLOCK_TIMESTAMP) as BLOCK_DATE,
TRANSACTION_HASH,
TRACE_ID,
TO_ADDRESS AS ACCOUNT,
FROM_ADDRESS AS BUNDLER,
'transfer' AS TXN_TYPE,
INPUT
FROM OPTIMISM.RAW.TRACES
WHERE FROM_ADDRESS = '0x2800f6eb0d1c000000819e0000008ac70c00b97b' --TRANSFER
AND SELECTOR = '0x6a761202' -- execTransaction
AND CALL_TYPE = 'call'
AND ERROR IS NULL
{% if is_incremental() %}
AND BLOCK_TIMESTAMP >= CURRENT_TIMESTAMP() - interval '3 day' 
{% endif %}

UNION ALL 
SELECT 
BLOCK_TIMESTAMP,
TRANSACTION_HASH,
TRACE_ID,
TO_ADDRESS AS ACCOUNT,
FROM_ADDRESS AS BUNDLER,
'swap' AS TXN_TYPE,
INPUT
FROM OPTIMISM.RAW.TRACES
WHERE FROM_ADDRESS = '0x000000561d8419c30093009fe70082e10a00007b' --SWAP
AND SELECTOR = '0x6a761202' -- execTransaction
AND CALL_TYPE = 'call'
AND ERROR IS NULL
{% if is_incremental() %}
AND BLOCK_TIMESTAMP >= CURRENT_TIMESTAMP() - interval '3 day' 
{% endif %}

UNION ALL 
SELECT
BLOCK_TIMESTAMP,
TRANSACTION_HASH,
TRACE_ID,
CONCAT('0x', SUBSTRING(INPUT, 99, 40)) AS ACCOUNT,
FROM_ADDRESS AS BUNDLER,
'claim' AS TXN_TYPE,
INPUT
FROM OPTIMISM.RAW.TRACES 
WHERE FROM_ADDRESS = '0xa0375658570f8459ddd8c753e288f5a25b4520e1' --CLAIM
AND SELECTOR = '0xa41e6ceb' --claim
AND CALL_TYPE = 'call'
AND ERROR IS NULL
{% if is_incremental() %}
AND BLOCK_TIMESTAMP >= CURRENT_TIMESTAMP() - interval '3 day' 
{% endif %}

UNION ALL 
SELECT
BLOCK_TIMESTAMP,
TRANSACTION_HASH,
TRACE_ID,
CONCAT('0x', SUBSTRING(INPUT, 99, 40)) AS ACCOUNT,
FROM_ADDRESS AS BUNDLER,
'claim_reserved' AS TXN_TYPE,
INPUT
FROM OPTIMISM.RAW.TRACES
WHERE FROM_ADDRESS = '0x07f8757ee74f1623e7e96e32c13e5f8edef94f14' --RESERVED
AND CALL_TYPE = 'call'
AND ERROR IS NULL
{% if is_incremental() %}
AND BLOCK_TIMESTAMP >= CURRENT_TIMESTAMP() - interval '3 day' 
{% endif %}